name: Teardown Revive Node & ETH-RPC
description: Stop background revive-dev-node and eth-rpc processes and upload logs

inputs:
  upload-logs:
    description: Upload logs as artifact
    required: false
    default: 'true'
  artifact-name:
    description: Artifact name
    required: false
    default: local-polkavm-logs

runs:
  using: composite
  steps:
    - name: Stop processes
      shell: bash
      run: |
        if [ -f eth-rpc.pid ]; then kill -TERM $(cat eth-rpc.pid) || true; fi
        if [ -f revive-node.pid ]; then kill -TERM $(cat revive-node.pid) || true; fi

    - name: Upload logs
      if: ${{ inputs.upload-logs == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: |
          revive-node.log
          eth-rpc.log


