name: Setup ETH-RPC Proxy
description: Build and start the pallet-revive-eth-rpc adapter (expects revive node running)

inputs:
  polkadot-sdk-ref:
    description: Git ref (commit/branch/tag) for polkadot-sdk
    required: false
    default: 8e2b6f742a38bb13688e12abacded0aab2dbbb23
  cache-key-suffix:
    description: Suffix to vary the cache key
    required: false
    default: ''
  sdk-path:
    description: Path to polkadot-sdk checkout
    required: false
    default: polkadot-sdk
  use-prebuilt:
    description: Use prebuilt binaries from binaries-root instead of building
    required: false
    default: 'false'
  binaries-root:
    description: Root folder containing prebuilt binaries (e.g., common-binaries)
    required: false
    default: common-binaries
  arch:
    description: Architecture folder name under binaries-root (e.g., linux-amd64)
    required: false
    default: linux-amd64
  fail-if-missing:
    description: If use-prebuilt is true and binaries are missing, fail instead of building
    required: false
    default: 'false'

outputs:
  eth-rpc-pid:
    value: ${{ steps.start.outputs.eth_rpc_pid }}

runs:
  using: composite
  steps:
    - name: Prepare eth-rpc (prebuilt or build)
      shell: bash
      run: |
        set -euo pipefail
        SDK_PATH="${{ inputs.sdk-path }}"
        BIN_ROOT="${{ inputs.binaries-root }}"
        REF="${{ inputs.polkadot-sdk-ref }}"
        ARCH="${{ inputs.arch }}"
        PREBUILT_SRC="$BIN_ROOT/$REF/$ARCH/eth-rpc"
        DEST_DIR="$SDK_PATH/target/release"
        mkdir -p "$DEST_DIR"
        if [ "${{ inputs.use-prebuilt }}" = "true" ]; then
          if [ -f "$PREBUILT_SRC" ]; then
            echo "Using prebuilt eth-rpc from $PREBUILT_SRC"
            install -m 0755 "$PREBUILT_SRC" "$DEST_DIR/eth-rpc"
          else
            echo "Prebuilt eth-rpc not found at $PREBUILT_SRC"
            if [ "${{ inputs.fail-if-missing }}" = "true" ]; then
              exit 1
            fi
            echo "Falling back to build from source"
            cd "$SDK_PATH"
            git checkout "$REF"
            cargo build --locked -p pallet-revive-eth-rpc --bin eth-rpc --release
          fi
        else
          cd "$SDK_PATH"
          git checkout "$REF"
          cargo build --locked -p pallet-revive-eth-rpc --bin eth-rpc --release
        fi

    - name: Save target cache
      if: always()
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.sdk-path }}/target
        key: ${{ runner.os }}-polkadot-sdk-target-${{ inputs.polkadot-sdk-ref }}-${{ inputs.cache-key-suffix }}

    - name: Start ETH-RPC adapter
      id: start
      shell: bash
      run: |
        nohup "${{ inputs.sdk-path }}"/target/release/eth-rpc --dev > eth-rpc.log 2>&1 &
        echo $! > eth-rpc.pid
        echo "eth_rpc_pid=$(cat eth-rpc.pid)" >> $GITHUB_OUTPUT


