name: Fetch Polkadot SDK
description: Clone (or update) polkadot-sdk at a specific ref and restore build cache

inputs:
  ref:
    description: Git ref (commit/branch/tag) for polkadot-sdk
    required: false
    default: 8e2b6f742a38bb13688e12abacded0aab2dbbb23
  path:
    description: Directory to place the repository
    required: false
    default: polkadot-sdk
  cache-key-suffix:
    description: Suffix to vary the cache key
    required: false
    default: ''

outputs:
  path:
    description: Path to the polkadot-sdk checkout
    value: ${{ steps.out.outputs.path }}
  target_cache_hit:
    description: 'Whether compiled dependencies cache was hit'
    value: ${{ steps.restore_compiled_deps.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Clone or update
      shell: bash
      run: |
        if [ -d "${{ inputs.path }}" ]; then
          cd "${{ inputs.path }}"
          git fetch --all --tags --prune
          git checkout ${{ inputs.ref }}
        else
          git clone https://github.com/paritytech/polkadot-sdk.git "${{ inputs.path }}"
          cd "${{ inputs.path }}"
          git checkout ${{ inputs.ref }}
        fi

    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
        key: ${{ runner.os }}-cargo-deps-${{ hashFiles('polkadot-sdk/**/Cargo.lock') }}-${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-cargo-deps-

    - id: restore_compiled_deps
      name: Cache compiled dependencies
      uses: actions/cache@v4
      with:
        path: ${{ inputs.path }}/target/release/deps
        key: ${{ runner.os }}-deps-${{ hashFiles('polkadot-sdk/**/Cargo.lock') }}-${{ inputs.ref }}-${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-deps-${{ hashFiles('polkadot-sdk/**/Cargo.lock') }}-
          ${{ runner.os }}-deps-

    - name: Cache target incremental
      uses: actions/cache@v4
      with:
        path: ${{ inputs.path }}/target/release/incremental
        key: ${{ runner.os }}-incremental-${{ inputs.ref }}-${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-incremental-

    - id: out
      shell: bash
      run: echo "path=${{ inputs.path }}" >> $GITHUB_OUTPUT


