name: Build Revive Binaries

on:
  workflow_dispatch:
    inputs:
      polkadot-sdk-ref:
        required: true
        type: string
  schedule:
    - cron: '0 2 * * *'

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    env:
      # Force-disable GHA backend for sccache to avoid outages
      SCCACHE_GHA_ENABLED: "false"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: ./.github/actions/setup-rust

      - name: Validate sccache (fallback to no cache if broken)
        shell: bash
        run: |
          set -e
          if command -v sccache >/dev/null 2>&1; then
            # Try to start server with disk cache only
            if ! sccache --start-server; then
              echo "sccache failed to start, disabling compiler wrapper"
              echo "RUSTC_WRAPPER=" >> $GITHUB_ENV
            else
              sccache --show-stats || true
            fi
          fi

      - name: Fetch SDK
        id: fetch
        uses: ./.github/actions/fetch-polkadot-sdk
        with:
          ref: ${{ inputs.polkadot-sdk-ref }}

      - name: Build binaries
        run: |
          export SCCACHE_ERROR_LOG=$RUNNER_TEMP/sccache-error.log
          export SCCACHE_LOG=info
          cd polkadot-sdk
          cargo build --locked --release \
            -p revive-dev-node --bin revive-dev-node \
            -p pallet-revive-eth-rpc --bin eth-rpc

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: revive-binaries-${{ inputs.polkadot-sdk-ref }}
          path: |
            polkadot-sdk/target/release/revive-dev-node
            polkadot-sdk/target/release/eth-rpc
          retention-days: 30


